### ISSUE TITLE
Adhere to semver

### ISSUE THREAD

**Issue by nwinch** [Prismatik/auth#39]
Should `auth` adhere to semver?  So far, there have been some major releases with no change in versioning.  As this service is now rolled out for multiple projects, this feels quite important.

It will give us the confidence to update without having to worry about projects breaking.

**Comment by davidbanham** [comment]
There have been no breaking changes to the API, so there's been no need to increment the major. That's the properly important bit of semver. The minor and patch versions are really just about marketing and communication to users. We _should_ be updating those, but it's a nice to have rather than a must-have.

**Comment by nwinch** [comment]
Hmm I may have been thinking about `auth-driver`.. scrap the major release comment!

> but it's a nice to have rather than a must-have
This though.. shouldn't we keep all our open source projects consistent and use semver?  Why have some use it, and some not?

**Comment by davidbanham** [comment]
We definitely _should_ be adhering to semver, no question. It's just a matter of the time to do it, I guess. I've got a sec now. I'll bump the minor.
